#!/bin/sh

# Set these paths appropriately

BIN=/home/alexis/Documents/EPFL/MS3/Project/python/TreeTagger/bin
CMD=/home/alexis/Documents/EPFL/MS3/Project/python/TreeTagger/cmd
LIB=/home/alexis/Documents/EPFL/MS3/Project/python/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
