#!/bin/sh

# Set these paths appropriately

BIN=/home/alexis/Documents/EPFL/MS3/Project/TreeTagger/bin
CMD=/home/alexis/Documents/EPFL/MS3/Project/TreeTagger/cmd
LIB=/home/alexis/Documents/EPFL/MS3/Project/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
