#!/bin/sh

# Set these paths appropriately

BIN=/Users/cybor/Sites/3n-tools/python/tree-tagger/bin
CMD=/Users/cybor/Sites/3n-tools/python/tree-tagger/cmd
LIB=/Users/cybor/Sites/3n-tools/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
