#!/bin/sh

# Set these paths appropriately

BIN=/Users/cybor/Sites/3n-tools/python/tree-tagger/bin
CMD=/Users/cybor/Sites/3n-tools/python/tree-tagger/cmd
LIB=/Users/cybor/Sites/3n-tools/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
