#!/bin/sh

# Set these paths appropriately

BIN=/home/alexis/Documents/EPFL/MS3/Project/treetagger/bin
CMD=/home/alexis/Documents/EPFL/MS3/Project/treetagger/cmd
LIB=/home/alexis/Documents/EPFL/MS3/Project/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
