#!/bin/sh

# Set these paths appropriately

BIN=/home/alexis/Documents/EPFL/MS3/Project/treetagger/bin
CMD=/home/alexis/Documents/EPFL/MS3/Project/treetagger/cmd
LIB=/home/alexis/Documents/EPFL/MS3/Project/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian-utf8.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
